name: release-message-nest

on:
  push:
    # run only against tags
    tags:
      - '*'
#  workflow_dispatch:  #

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:

  build-and-release-message-nest:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: prod

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.2'
          cache: true

      - name: Install npm dependencies
        run: npm i
        working-directory: web/

      - name: Run npm build
        run: export NODE_ENV=prod && npm run build
        working-directory: web/

      - name: Check build static
        run: ls dist/ -la
        working-directory: web/

      - name: Git File Restore
        run:  touch dist/.gitkeep
        working-directory: web/

      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
          # distribution:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}


